=== zhangbogh/eyes/eyes/input/bizmonitor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/bizmonitor"
        xmlns:tns="http://www.example.org/bizmonitor" elementFormDefault="qualified">
    <element name="nodes">
        <complexType>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element ref="tns:BasicdbCheck"/>
                <element ref="tns:SnapdbCheck"/>
                <element ref="tns:DbPort"/>
                <element ref="tns:FtpConn"/>
                <element ref="tns:Mail"/>
                <element ref="tns:SequencedbCheck"/>
                <element ref="tns:FileCheck"/>
                <element ref="tns:ComplexDbCheck"/>
            </choice>
        </complexType>
    </element>

    <complexType name="basenode">
        <attribute name="id" type="string" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="mailid" type="string" use="required"/>
        <attribute name="shownames" type="string" use="required"/>
        <attribute name="error" type="string" use="required"/>
    </complexType>

    <element name="DbPort">
        <complexType>
            <attribute name="id" type="string" use="required"/>
            <attribute name="url" type="string" use="required"/>
            <attribute name="name" type="string" use="required"/>
            <attribute name="password" type="string" use="required"/>
        </complexType>
    </element>

    <element name="FtpConn">
        <complexType>
            <attribute name="id" type="string" use="required"/>
            <attribute name="host" type="string" use="required"/>
            <attribute name="port" type="string" use="optional"/>
            <attribute name="name" type="string" use="required"/>
            <attribute name="password" type="string" use="required"/>
        </complexType>
    </element>

    <element name="Mail">
        <complexType>
            <attribute name="id" type="string" use="required"/>
            <attribute name="address" type="string" use="required"/>
        </complexType>
    </element>

    <element name="BasicdbCheck">
        <complexType>
            <complexContent>
                <extension base="tns:basenode">
                    <sequence>
                        <element name="sql" type="string" minOccurs="0" maxOccurs="1"/>
                    </sequence>
                    <attribute name="bdid" type="string" use="required"/>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="SnapdbCheck">
        <complexType>
            <complexContent>
                <extension base="tns:basenode">
                    <sequence>
                        <element name="sql" type="string" minOccurs="0" maxOccurs="1"/>
                    </sequence>
                    <attribute name="bdid" type="string" use="required"/>
                    <attribute name="filepath" type="string" use="required"/>
                    <attribute name="checkconditionclass" type="string" use="required"/>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="FileCheck">
        <complexType>
            <complexContent>
                <extension base="tns:basenode">
                    <sequence>
                        <element name="file" type="string" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                    <attribute name="dir" type="string" use="required"/>
                    <attribute name="cron" type="string" use="required"/>
                    <attribute name="ftpid" type="string" use="required"/>
                    <attribute name="minsize" type="int" use="optional"/>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="SequencedbCheck">
        <complexType>
            <complexContent>
                <extension base="tns:basenode">
                    <sequence>
                        <element name="sql" type="string" minOccurs="0" maxOccurs="1"/>
                        <element name="sequencekey" type="string" minOccurs="0" maxOccurs="1"/>
                        <element name="sequencevalue" type="string" minOccurs="0" maxOccurs="1"/>
                        <element name="followvalue" type="string" minOccurs="0" maxOccurs="1"/>
                        <element name="sequencetype" type="int" minOccurs="0" maxOccurs="1"/>
                    </sequence>
                    <attribute name="bdid" type="string" use="required"/>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="ComplexDbCheck">
        <complexType>
            <complexContent>
                <extension base="tns:basenode">
                    <sequence>
                        <element name="sql" type="string" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                    <attribute name="bdid" type="string" use="required"/>
                    <attribute name="checkconditionclass" type="string" use="required"/>
                </extension>
            </complexContent>
        </complexType>
    </element>
</schema>

=== zhangbogh/eyes/eyes/input/union_day_divide_check.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:nodes xmlns:tns="http://www.example.org/bizmonitor"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/bizmonitor ./bizmonitor.xsd ">
	<tns:DbPort url="jdbc:mysql://cp01-rd-union003.cp01.baidu.com:8910/union4"
		name="union" password="uniondb123" id="computedb" />
	<tns:Mail address="yaoli@baidu.com" id="unionrd" />

	<!-- 基础功能验证 -->
	<tns:BasicdbCheck name="网盟分成波动数据" bdid="computedb" id="1"
		mailid="unionrd" error="" shownames="日期,数量,展现量,点击,收入,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(viewtimes),sum(click),sum(income),sum(divide) 
				from daydomaindividesttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="APP分成波动数据" bdid="computedb"
		id="2" mailid="unionrd" error="" shownames="日期,数量,展现量,点击,CPC收入,CPM收入,用户CPC分成,用户CPM分成,渠道CPC收入,渠道CPM收入">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(viewtimes),sum(click),sum(cpcincome),sum(cpmincome),sum(usercpcdivide),sum(usercpmdivide),sum(chcpcdivide),sum(chcpmdivide) from dayappdividesttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="搜索分成波动数据" bdid="computedb" id="2"
		mailid="unionrd" error="" shownames="日期,数量,访问量,展现量,点击,收入,修正后收入,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(visit),sum(viewtimes),sum(click),sum(income),sum(adjustincome),sum(divide) from daysearchsttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="软件分成波动数据" bdid="computedb" id="2"
		mailid="unionrd" error="" shownames="日期,数量,安装量,访问量,展现量,点击,收入,修正后收入,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(install),sum(visit),sum(viewtimes),sum(click),sum(income),sum(adjustincome),sum(divide) from daysoftwaresttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="搜索分渠道分成波动数据" bdid="computedb"
		id="2" mailid="unionrd" error="" shownames="日期,数量,访问量,展现量,点击,收入,修正后收入,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(visit),sum(viewtimes),sum(click),sum(income),sum(adjustincome),sum(divide) from daychannelsearchsttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="团购分成波动数据" bdid="computedb" id="2"
		mailid="unionrd" error="" shownames="日期,数量,消费次数,收入,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(consumetimes),sum(income),sum(divide) 
				from daytuansttt
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
	<tns:BasicdbCheck name="DAN分成波动数据" bdid="computedb"
		id="2" mailid="unionrd" error="" shownames="日期,数量,展现量,请求量,修正前期请求量,分成">
		<tns:sql>
			<![CDATA[
				select countdate,count(*),sum(viewtimes),sum(REQUESTTIMES),sum(VIEWTIMESBEFORE),sum(divide) 
				from daydansttt 
				where countdate > date_format( date_add(now(), interval -32 day),'%Y%m%d')
				group by countdate;
			]]>
		</tns:sql>
	</tns:BasicdbCheck>
</tns:nodes>
